version: 2
jobs:
  build:
    docker:
      - image: gnuton/asuswrt-merlin-toolchains-docker
        environment:
          MAKEFLAGS: "-j 1"
          PROJECT_DIR: "/root/project"
          MODEL: "dsl-ac68u"
          CHANGELOG_FILE: "/tmp/CHANGELOG"
          SDK_PLATFORM: "sdk"
    steps:
      - checkout
      - run:
          name: Set EXTENDNO
          shell: /bin/bash
          command: |
            if [ -z "${CIRCLE_TAG}" ]; then
              echo "Nothing to do. Not a release."
            else
              EXT_TAG="$(echo -n $CIRCLE_TAG | sed -e "s/[0-9._]\\+\\-//g")"
              sed -i "s/EXTENDNO=.*/EXTENDNO=${EXT_TAG}/g" release/src-rt/version.conf
            fi
      - run:
          name: Generate changelog (only for tags)
          command: |
            REGXP_TO_MATCH=.*gnuton.*
            if [[ ${CIRCLE_TAG} =~ ${REGXP_TO_MATCH} ]]; then
              CURRENT_TAG=${CIRCLE_TAG}
              PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -v snapshot | grep ${REGXP_TO_MATCH} | head -n 2 | sed -n 2p)
              echo "Generating logs between the tags ${PREVIOUS_TAG} and ${CURRENT_TAG}"
              echo "Changes from the latest stable gnuton build (${PREVIOUS_TAG}):" > "${CHANGELOG_FILE}"
              git log ${PREVIOUS_TAG}...${CURRENT_TAG} --pretty=format:'* %s' --reverse | grep -v 'Merge branch' >> "${CHANGELOG_FILE}"
              cat "${CHANGELOG_FILE}"
            else
              echo "No changelog to generate. Changelog is generated only for tags matching ${REGXP_TO_MATCH}";
            fi;
      - run:
          name: Setup toolchain
          command: |
            # For brcm-arm-sdk/ Broadcom SDK6/SDK7 ARM platform (RT-AC56 upto RT-AC5300)
            if [ "$SDK_PLATFORM" == "sdk" ]; then
              echo "Setting up brcm-arm-sdk toolchains"
              rm ${PROJECT_DIR}/release/src-rt-6.x.4708/toolchains
              ln -s /opt/am-toolchains/brcm-arm-sdk  ${PROJECT_DIR}/release/src-rt-6.x.4708/toolchains
            fi
            # For brcm-arm-hnd/ Broadcom HND ARM platform (RT-AC86U)
            if [ "$SDK_PLATFORM" == "hnd" ]; then
              echo "Setting up brcm-arm-hnd toolchains"
              ln -s ~/am-toolchains/brcm-arm-hnd /opt/toolchains
              echo "export TOOLCHAIN_BASE=/opt/toolchains" >> ~/.profile
              echo "export LD_LIBRARY_PATH=$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/lib" >> ~/.profile
              echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
              echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
            fi
            # For  brcm-arm-hnd/ Broadcom HND ARM platform 802.11ax models (eg HND AX ARM (RT-AX88U))
            if [ "$SDK_PLATFORM" == "hnd-ax" ]; then
              echo "Setting up brcm-arm-hnd-ax toolchains"
              ln -s ~/am-toolchains/brcm-arm-hnd /opt/toolchains
              echo "export TOOLCHAIN_BASE=/opt/toolchains" >> ~/.profile
              echo "export LD_LIBRARY_PATH=$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/lib" >> ~/.profile
              echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ~/.profile
              echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin" >> ~/.profile
            fi
      - run:
          name: Build firmware
          shell: /bin/bash
          no_output_timeout: 120m
          command: | 
            cd ${PROJECT_DIR}/release/src-rt-6.x.4708/
            ls
            pwd
            make clean || echo "maybe already clean, so if it fails please continue"
            make ${MODEL} | tee "/tmp/build.log" # | grep -i "error\|-e"
            ls ${PROJECT_DIR}/release/src-rt-6.x.4708/image/

      - run:
          name: Prepare workspace
          command: |
            mkdir -p workspace/release
            cp ${PROJECT_DIR}/release/src-rt-6.x.4708/image/*.trx workspace/release
            cp ${PROJECT_DIR}/release/src-rt-6.x.4708/image/*.md5 workspace/release
            cp /tmp/build.log workspace/release
             if [ -z "${CIRCLE_TAG}" ]; then
              echo "No CHANGELOG to copy. Not a release build."
            else
              cp "${CHANGELOG_FILE}" workspace/release
            fi
      - persist_to_workspace:
          root: workspace
          paths:
            - release
  publish-github-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/release
      - run:
          name: "Publish Release on Github"
          command: |
            echo "Uploading release..."
            RELEASE_TITLE="Release: ${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -n "${RELEASE_TITLE}" -b "$(cat workspace/release/CHANGELOG)" ${CIRCLE_TAG} workspace/release/
  publish-github-ci-pre-release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: workspace
      - run: ls workspace/release
      - run:
          name: "Publish CI pre-release on Github"
          command: |
            echo "Uploading CI pre-release..."
            RELEASE_TITLE="Snapshot: ${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n "${RELEASE_TITLE}" -b "$(cat workspace/release/CHANGELOG)" -delete -prerelease ${CIRCLE_TAG} workspace/release/
 
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
               - master
               - mainline
      - publish-github-release:
          filters:
            tags:
              only: /[0-9]+.*gnuton.*/
            branches:
              ignore: /.*/
          requires:
            - build
      - publish-github-ci-pre-release:
          filters:
            tags:
              only: /gnuton-snapshot-.*/
            branches:
              ignore: /.*/
          requires:
            - build
