name: Containers
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    build-job:
        name: build firmware
        runs-on: ubuntu-latest
        container: 
          image: gnuton/asuswrt-merlin-toolchains-docker:latest
          env:
            MERLINUPDATE: "y"
            MODEL: "rt-ax28u"
            SDK: "src-rt-5.02axhnd.675x"
            GIT_REPO: "https://github.com/gnuton/asuswrt-merlin.ng.git"
          options: --user root 
          volumes:
            - ${{ github.workspace }}:/project
        steps:
          - name: "Fetch code" 
            run: |
              pwd
              echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event." 
              echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
              cd /project
              git clone --single-branch --branch master $GIT_REPO
              ls /home/docker
          - name: "Build"
            run: |
              cd "/project/"
              ls
              cd "asuswrt-merlin.ng"
              ls
              cd "release/$SDK"
              make "$MODEL"
              echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
              echo "🍏 This job's status is ${{ job.status }}."
